### ISSUE TITLE
포토후기 적립금 기간 만료 시 소멸 처리

### ISSUE THREAD

**Issue by arckjh** [arckjh/mustit-doc#104]
## 업무 요청 내용
상품후기 등록시 지금되는 적립금의 경우, 적립시점 +1년뒤 적립금 소멸처리가 되고있는데, 포토후기에 대해서는 기간만료 소멸처리가 미진행중인것으로 알고있습니다. 본건에 대해 상품후기와 동일하게 +1년뒤 소멸처리를 요청드리니 작업사항 및 일정 확인 부탁드리겠습니다.

## 솔루션
  - 스케쥴링 작업 처리 진행
  - ft-backoffice로 분기 처리 후 dev 브랜치로 풀리퀘스트 처리 바람
  - 이외에 다른 이슈 사항이 있으시면 슬랙 피드백 부탁드립니다.

**Comment by devyih** [comment]
# 분석/설계
- 스케줄링(Crontab) 작업 필요
  > - 포토후기 적립금 기간 만료 시 소멸 처리

- 스케줄링(Crontab) 외 주문, 환불 시 코드 개발 필요
  > - 적립 데이터는 다중의 행으로 적재되나 사용 데이터는 가변적임
  > - 이에 적립금 사용, 환불 시 기존 정책에 의거한 코드 개발 필요

- 기존 포토후기 적립금 데이터에 대해 소멸 적립금 데이터 마이그레이션 작업 필요

# 이슈
- 사용하지 않은 기존 포토후기 적립금 데이터는 어떻게 처리할지에 대한 확인 필요
