### ISSUE TITLE
2019년 1월 4주차 주간보고

### ISSUE THREAD

**Issue by arckjh** [arckjh/mustit-doc#108]
## 1월 4주차 주간보고 기록
* 기록 포맷
  - 프론트 UX/UI 개선 개발
  - 서비스 운영 개선 개발
  - 광고/이벤트 운영 기능 개발
  - 신규 프로젝트 개발
  - IT 인프라 개선 및 기술 이슈 해결
* 배포까지 완료해야 업무 완료이며 이제 모든 업무 완료일을 배포일 기준으로 세팅 바람 
* 주문 컴포넌트는 devkim 님이 취합해서 기록 남겨주세요
* 금요일 3시까지 기록 부탁

**Comment by devyih** [comment]
# 금주
- 서비스 운영 개선 개발
  > - 기획전 리뉴얼 : 결함 및 수정 처리 (완료)
  > - 포토후기 적립금 기간 만료 시 소멸 처리 (~1/25)

- IT 인프라 개선 및 기술 이슈 해결
  > - 백오피스 분리 시 이슈 검토 (완료)


# 차주
- 서비스 운영 개선 개발
  > - 포토후기 적립금 기간 만료 시 소멸 처리 (~1/25)

- IT 인프라 개선 및 기술 이슈 해결
  > - 백오피스 분리 이행 (~2/1)

**Comment by devyjh** [comment]
**금주**
* 서비스 운영 개선 개발
  - 상품 속성 관리 페이지 지연(완료)
    + https://github.com/arckjh/mustit-doc/issues/99
  - 10만원 미만 상품 데이터 추출 요청(완료)
    + https://github.com/arckjh/mustit-doc/issues/100
  - 상품 수정시 잇포인트 버그(완료)
    + https://github.com/arckjh/mustit-doc/issues/98
  - 깜짝배송 일괄 설정 요청(완료)
    + https://github.com/arckjh/mustit-doc/issues/92
  - API 사용 요청 응대 (1/8~)
    + https://github.com/arckjh/mustit-doc/issues/79
  - 쿠차 EP 제작(~1/21)
    + https://github.com/arckjh/mustit-doc/issues/80
    + 쿠차측 피드백 지연.
    + 21일 까지 피드백 없을 경우, 자체적으로 일정 종료 예정.
* 신규 프로젝트 개발
  - 머스트잇 상품 속성 데이터 상용화 방안(~1/14)
    + https://github.com/arckjh/mustit-doc/issues/105
    + 개발팀장님께 보고 완료. 대표님 보고일정 미정.
---
**차주**
* 서비스 운영 개선 개발
  - API 사용 요청 응대 (1/8~)
    + https://github.com/arckjh/mustit-doc/issues/79
* 신규 프로젝트 개발
  - 상품 쿠폰 고도화(~1/31)
    + https://github.com/arckjh/mustit-doc/issues/86
    + 개발 목표 종료일 1/28.
- 머스트잇 상품 속성 데이터 상용화 방안(~1/14)
    + https://github.com/arckjh/mustit-doc/issues/105
    + 개발팀장님께 보고 완료. 대표님 보고일정 미정.

**Comment by devujh** [comment]
금주
-----
* 프론트 UX/UI 개선 개발
  - UI/UX 컴포넌트 구조 분석/설계 (완료)  
  
* 서비스 운영 개선 개발
  - 개인통관부호 입력 UI개선 (완료)
  - 모바일 주문상세 '상세정보' 버튼명 수정 ( 퍼블리싱 완료 / 배포 ~01. 25 )

 * 신규 프로젝트 개발
  - 깜짝배송 서비스 개선 (퍼블리싱 완료 ~01.22 / 배포미정)

차주
-----
* 프론트 UX/UI 개선 개발
  - 판매자 상품등록페이지 UI 개선 (~ 01. 25)
  - UI/UX 컴포넌트 환경 구성 (~ 02. 07)
  
* 신규 프로젝트 개발
  - 깜짝배송 서비스 개선 (퍼블리싱 완료 ~01.22 / 배포미정)

**Comment by devkhm** [comment]
**금주**
* 서비스 운영 개선 개발
  - 배송비 판매자 수수료 변경의 건(완료)
    + https://github.com/arckjh/mustit-doc/issues/89
  - 판매자공지사항 - 조회수 추가(완료)
    + https://github.com/arckjh/mustit-doc/issues/95
  - 개인통관부호 입력 UI 변경(완료)
    + https://github.com/arckjh/mustit-doc/issues/67
  - 깜짝배송 서비스 개선(1/17~)
    + https://github.com/arckjh/mustit-doc/issues/97
    + QA, 배포 일정 미협의

* 장애 현황
  - 코드 저장소 이동(1/16~)
    + https://github.com/arckjh/mustit-doc/issues/84
    + 삼성페이 연동 이상유무 확인 (완료)
    + 오류 주문 삭제 처리 (완료)
    + 고객관리팀에서 요청하는 주문 장바구니 생성(완료예정)

---
**차주**
* 서비스 운영 개선 개발
  - 깜짝배송 서비스 개선(1/17~)
    + https://github.com/arckjh/mustit-doc/issues/97
    + QA, 배포 일정 미협의
  - MO 주문상세 '상세정보' 버튼명 수정(~1/24)
    + https://github.com/arckjh/mustit-doc/issues/91
  - 1대1문의하기 이미지 첨부 기능 추가(1/24~1/28)
    + https://github.com/arckjh/mustit-doc/issues/112

**Comment by devjjw2** [comment]
# 금주
- 셀럽스타일 + 스크립트 관련 수정 (완료)
- 원더쇼핑 핫딜 EP (완료) 
# 차주
- DDOS 차단 기능 개발 (01/21 ~ 01/22)
- 카톡, 카스 공유 에러 처리 *DDOS 차단 기능우선처리관계로 일정 변경 (01/23 ~ 01/24)
- 404 & 500 통합에러처리 (~ 01/25)
- 이벤트 당첨자 발표 페이지 처리 ( 01/29)
