### ISSUE TITLE
[정기] 원더쇼핑 패밀리세일

### ISSUE THREAD

**Issue by devyih** [arckjh/mustit-doc#74]
# 요청
- 마케팅 산출물 : https://drive.google.com/drive/folders/1vHCKwGidns1TmGZDNXrDH5dJ6N4tG06H
- Taskworld : https://asia-enterprise.taskworld.com/5b0df518a3b486513ef4f739/#/project/371/task/8648
- Slack https://mustit.slack.com/archives/CDK4AQLGJ/p1544517425054500

# 업무
- 데이터 부하 분산 처리를 위한 인프라 구축 및 부하 테스트 진행 (김정환 / 12. 17 ~ 12. 21)
- 주요 페이지 데이터 부하 분산 처리 (김현민 / 12. 18 ~ 12. 21)
- 콘텐츠 퍼블리싱 (유지호 / 12. 20)
- 쿠폰 다운로드 기능 예외 처리 (오종윤 / 12. 20 ~ 12. 21)
- 특가 상품 노출 예외 처리 (김현민 / 12. 21)

**Comment by devkhm** [comment]
[소프트웨어 처리]
1. 페이지 진입 시 MASTER DB 에 INSERT, UPDATE, DELETE 선 처리 후 CONNECT CLOSE.
2. 이후의 SELECT 는 SLAVE DB CONNECT 하여 처리.

처리되는 페이지는 상품상세, 상품검색 페이지를 우선으로 처리 하되 시간적 여유가 생긴다면 access log 를 분석하여 페이지 접속 빈도가 많은 순으로 추가로 처리할 예정.
