### ISSUE TITLE
콘텐츠 도메인 분석

### ISSUE THREAD

**Issue by arckjh** [arckjh/mustit-doc#76]
## 마케팅 도메인 학습

![이미지](https://s3.ap-northeast-2.amazonaws.com/mustit-dev-upload/arckjh/20190107_architecture.png)

### [콘텐츠 서비스]
* 웹사이트 '기획전 / 이벤트 / 매거진 / 샵 페이지' 코드 분석
* 쿠폰 시스템 분석 : [https://drive.google.com/open?id=1dxND2qEpwiYTeU8VokfwEDorRTfO8fvm](https://drive.google.com/open?id=1dxND2qEpwiYTeU8VokfwEDorRTfO8fvm)
* 백오피스 및 서버 구조 분석 : [https://drive.google.com/open?id=1gH2dVIq4R3Hq81d8HvSi9H_oTeeNJBio](https://drive.google.com/open?id=1gH2dVIq4R3Hq81d8HvSi9H_oTeeNJBio)

### [공통 서비스]
* 계정/세션 관리 코드 분석
* 3rd party 코드 분석

### [문서 작성 방법]
* 마크다운 사용법 : [https://gist.github.com/ihoneymon/652be052a0727ad59601](https://gist.github.com/ihoneymon/652be052a0727ad59601)
* 이미지 업로드 방법 : AWS Web Console > S3 > mustit-dev-upload > devjjw 경로 확인

**Comment by devjjw2** [comment]
# 코드분석
      > 담당업무 코드분석을 통한 테이블 구조를 도식화 하였습니다.

- 기획전 
![default](https://user-images.githubusercontent.com/46430983/51103584-afdf9480-1826-11e9-8b34-154971278e58.png)
- 이벤트
![default](https://user-images.githubusercontent.com/46430983/51103713-1e245700-1827-11e9-859b-c7a2278d8e19.png)
- 쿠폰
![default](https://user-images.githubusercontent.com/46430983/51103897-b7536d80-1827-11e9-91e6-b10ef7cfc265.png)
- 매거진
![default](https://user-images.githubusercontent.com/46430983/51103956-f08bdd80-1827-11e9-8122-3cb65597c7b4.png)
- 샵
![default](https://user-images.githubusercontent.com/46430983/51103999-1618e700-1828-11e9-9fa4-6f5b60f342dd.png)
- 계정 / 세션
![default](https://user-images.githubusercontent.com/46430983/51104105-7b6cd800-1828-11e9-935c-1f7989d5c41b.png)

**Comment by arckjh** [comment]
수고 하셨습니다.
완료 하신 후 클로징 처리 및 프로젝트 칸반보드에서 배포/완료로 옮기시면 됩니다.
